version: '3.8'

services:
  app:
    build: .
    ports:
      - "9090:8080"
    environment:
      - DB_HOST=db
      - DB_PORT=5432
      - DB_USER=postgres
      - DB_PASS=postgres
      - DB_NAME=persondb
    depends_on:
      - db
    volumes:
      - .:/app 
    restart: unless-stopped

  db:
    image: postgres:13
    environment:
      - POSTGRES_DB=persondb
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
    ports:
      - 5436:5432
    volumes:
      - postgres_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 5s
      timeout: 5s
      retries: 5

volumes:
  postgres_data: